targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/controller/*.dart
            - lib/notifier/*.dart
            - lib/models_client/*.dart
            - lib/models_client/*/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/models_client/*.dart
            - lib/models_client/*/*.dart
        options:
          any_map: true
          explicit_to_json: true