name: amplify_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_flutter: ^0.6.1
  amplify_auth_cognito: ^0.6.1
  amplify_authenticator: ^0.2.1
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  simple_logger: ^1.9.0
  amplify_datastore: ^0.6.1
  intl: ^0.17.0

dependency_overrides:
  flutter_riverpod: ^2.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0
  pedantic_mono: ^1.19.2
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
